### ISSUE TITLE
multiple issues not displayed in recommendations

### ISSUE THREAD

**Issue by davidmarkclements** [nearform/node-clinic-doctor#114]
Here's a case of event loop delay and GC issue - but only GC issues displays in the recommendations tab 

![image](https://user-images.githubusercontent.com/1190716/38472887-f93394c4-3b86-11e8-8253-47915d553344.png)

**Comment by davidmarkclements** [comment]
also should all lines in memory usage be read?

**Comment by mcollina** [comment]
A severe memory issue often entails blocking the event loop, so it’s impossible to discern from both. In other terms, “the event loop is blocking because of high gc activity”.

However the code in that case does not seem to show such problematic memory usage.. can you share a repro?

**Comment by davidmarkclements** [comment]
In this case there's event loop blocking code and a memory leak - this is evident because a shorter duration load test only exposes the event loop issue whereas a longer one also teases out the memory leak 

Will share code once I've pushed it to a repro

**Comment by BridgeAR** [comment]
To me it is fine to detect one issue at a time. This keeps the UI simple and it is intended to run the tool multiple times until it does not show any issues anymore.

And since it is also difficult to distinguish the cases, I am closing this. If you still think it should be addressed, please show an example code and maybe also outline how it should be visualized.
