### ISSUE TITLE
Lots of failures on CITGM for various platforms

### ISSUE THREAD

**Issue by MylesBorins** [nearform/node-clinic-doctor#192]
https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/1654/nodes=win-vs2017/testReport/junit/(root)/citgm/_nearform_doctor_v3_7_1/
https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/1654/nodes=ppcle-ubuntu1404/testReport/junit/(root)/citgm/_nearform_doctor_v3_7_1/
https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/1654/nodes=ubuntu1804-docker/testReport/junit/(root)/citgm/_nearform_doctor_v3_7_1/

**Comment by mcollina** [comment]
@goto-bus-stop can you have a look?

**Comment by AlanSl** [comment]
I've had a quick look at this, there are two issues:

[x] - I've posted a PR for the Windows failure https://github.com/nearform/node-clinic-doctor/pull/195
[ ] - The Ubuntu / Pumpify failure looks like a timeout, with the pumpify error happening because the timeout is causing it to exit early. Written it up here: https://github.com/nearform/node-clinic-doctor/issues/196

Let's keep this issue open until both of those are fixed and released and we have confirmation that it passes CITGM

**Comment by MylesBorins** [comment]
more failures

https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/1660/testReport/

Skipping on debian and ubuntu for now

https://github.com/nodejs/citgm/pull/633

**Comment by MylesBorins** [comment]
Still flaky on multiple platforms, skipping on all platforms for now

https://github.com/nodejs/citgm/pull/637
